#Data WharteHouse cibersecurity

## Tabla de Hechos:
**(Fact_Security_Incidents)**

## Tabla de dimensiones:
**(Dim_Country, Dim_Industry, Dim_Attack, Dim_Defense, Dim_Time)**

# Paso 1: Importar las librerías necesarias

In [ ]:
# Paso 1
import pandas as pd

In [ ]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
%pwd
%cd "/content/drive/MyDrive/bootcamp/Proyecto"
%pwd
data = pd.read_csv('Global_Cybersecurity_Threats_2015-2024.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/bootcamp/Proyecto

# Paso 2: Definir una función para extraer el ID de archivo de Google Drive

In [ ]:
import sys
!{sys.executable} -m pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
# Paso 2.1: Cargar los DataSets desde archivo en Formato .CSV

# Carga la tabla de hechos
Fact_SecurityIncidents = pd.read_csv('Fact_SecurityIncidents.csv')

# Carga la tabla de dimensiones
Dim_Location = pd.read_csv('Dim_Location.csv')
Dim_Industry = pd.read_csv('Dim_Industry.csv')
Dim_Attack = pd.read_csv('Dim_Attack.csv')
Dim_Defense = pd.read_csv('Dim_Defense.csv')
Dim_Time = pd.read_csv('Dim_Time.csv')

In [ ]:
# Paso 3: Exploración de datos.
Fact_SecurityIncidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Incident_ID                          3000 non-null   int64
 1   Country_ID                           3000 non-null   int64
 2   Industry_ID                          3000 non-null   int64
 3   Attack_ID                            3000 non-null   int64
 4   Defense_ID                           3000 non-null   int64
 5   Time_ID                              3000 non-null   int64
 6   Financial Loss (in Million $)        3000 non-null   float64
 7   Number of Affected Users             3000 non-null   int64
 8   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(8)
memory usage: 211.1 KB

In [ ]:
Fact_SecurityIncidents.describe()

,Incident_ID,Country_ID,Industry_ID,Attack_ID,Defense_ID,Time_ID,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours)
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,5.497000,3.999667,47.667333,3.001000,5.545333,50.492970,504684.136333,36.476000
std,866.169729,2.853776,1.999083,27.197130,1.417863,2.854236,28.791415,289944.084972,20.570768
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,424.000000,1.000000
25%,750.750000,3.000000,2.000000,24.000000,2.000000,3.000000,25.757500,255805.250000,19.000000
50%,1500.500000,5.000000,4.000000,47.000000,3.000000,6.000000,50.795000,504513.000000,37.000000
75%,2250.250000,8.000000,6.000000,71.000000,4.000000,8.000000,75.630000,758088.500000,55.000000
max,3000.000000,10.000000,7.000000,96.000000,5.000000,10.000000,99.990000,999635.000000,72.000000

In [ ]:
Fact_SecurityIncidents.head()

,Incident_ID,Country_ID,Industry_ID,Attack_ID,Defense_ID,Time_ID,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours)
0,1,1,1,1,1,1,80.53,773169,63
1,2,1,2,2,2,1,62.19,295961,71
2,3,2,3,3,1,2,38.65,605895,20
3,4,3,4,4,3,3,41.44,659320,7
4,5,4,3,5,1,4,74.41,810682,68

In [ ]:
Fact_SecurityIncidents.tail()

,Incident_ID,Country_ID,Industry_ID,Attack_ID,Defense_ID,Time_ID,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours)
2995,2996,3,5,72,2,9,51.42,190694,52
2996,2997,8,4,94,1,6,30.28,892843,26
2997,2998,8,3,55,3,2,32.97,734737,30
2998,2999,3,3,34,2,7,32.17,379954,9
2999,3000,4,2,75,1,9,48.20,480984,64

In [ ]:
Fact_SecurityIncidents.shape

(3000, 9)

In [ ]:
# Paso 4:
# Contruir el DW (Integrando las tablas)

dw = (
    Fact_SecurityIncidents  # Tu tabla de hechos principal

    .merge(Dim_Location, on='Country_ID', how='left')

    .merge(Dim_Industry, on='Industry_ID', how='left')

    .merge(Dim_Attack, on='Attack_ID', how='left')

    # Unimos con la dimensión de Defensa
    .merge(Dim_Defense, on='Defense_ID', how='left')

    # Unimos con la dimensión de Tiempo (Año)
    .merge(Dim_Time, on='Time_ID', how='left')
)

# Mostrar el resultado final integrado
dw.head()

,Incident_ID,Country_ID,Industry_ID,Attack_ID,Defense_ID,Time_ID,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours),Country,Target Industry,Attack Type,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Year
0,1,1,1,1,1,1,80.53,773169,63,China,Education,Phishing,Hacker Group,Unpatched Software,VPN,2019
1,2,1,2,2,2,1,62.19,295961,71,China,Retail,Ransomware,Hacker Group,Unpatched Software,Firewall,2019
2,3,2,3,3,1,2,38.65,605895,20,India,IT,Man-in-the-Middle,Hacker Group,Weak Passwords,VPN,2017
3,4,3,4,4,3,3,41.44,659320,7,UK,Telecommunications,Ransomware,Nation-state,Social Engineering,AI-based Detection,2024
4,5,4,3,5,1,4,74.41,810682,68,Germany,IT,Man-in-the-Middle,Insider,Social Engineering,VPN,2018

# Resumen

1. Cargar: Los datos
2. Inspeccionar: La estructura de los datos
3. Integrar: La tabla de Hechos y sus dimensiones en un solo`DataFrame`
4. Analisis: De los datos Consolidados

Estos el pilar de cualquier pipeline de ETL (Extracción, la transformación y carga ) de estos datos sinteticos  Empleados en la Ciencia de datos o Business Intelligence.