# Análisis Exploratorio de Datos **(EDA)** y Transformación de Datos **(ETL)**

<!-- Talento Tech Logo Placeholder -->

**Curso:** Análisis de Datos Intermedio

**Docente:** Feibert Alirio Guzmán Pérez

**Autor:** Talento Tech

**proyecto** Análisis Estratégico de Ciberseguridad Global: Tendencias, Impacto Financiero y Defensa (2015-2024)

In [ ]:
# Librerias de trabajo
import pandas as pd

In [ ]:
import pandas as pd
from google.colab import drive

# Cargar el Dataset en .CSV

drive.mount('/content/drive')
%pwd
%cd "/content/drive/MyDrive/bootcamp/Proyecto"
%pwd
df = pd.read_csv('Global_Cybersecurity_Threats_2015-2024.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/bootcamp/Proyecto

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68
...,...,...,...,...,...,...,...,...,...,...
2995,UK,2021,Ransomware,Government,51.42,190694,Unknown,Social Engineering,Firewall,52
2996,Brazil,2023,SQL Injection,Telecommunications,30.28,892843,Hacker Group,Zero-day,VPN,26
2997,Brazil,2017,SQL Injection,IT,32.97,734737,Nation-state,Weak Passwords,AI-based Detection,30
2998,UK,2022,SQL Injection,IT,32.17,379954,Insider,Unpatched Software,Firewall,9
2999,Germany,2021,SQL Injection,Retail,48.20,480984,Unknown,Zero-day,VPN,64

In [ ]:
# Suma los valores nulos
print(df.isnull().sum())

# Da el valor de los nulos en %
df.isnull().sum() / len(df) * 100

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

Country                                0.0
Year                                   0.0
Attack Type                            0.0
Target Industry                        0.0
Financial Loss (in Million $)          0.0
Number of Affected Users               0.0
Attack Source                          0.0
Security Vulnerability Type            0.0
Defense Mechanism Used                 0.0
Incident Resolution Time (in Hours)    0.0
dtype: float64

## Cierre del Cuaderno

Agradecemos su tiempo y atención al revisar este cuaderno de Análisis Exploratorio de Datos (EDA) y Transformación de Datos (ETL). Hemos cubierto desde la comprensión inicial del dataset hasta el tratamiento de valores faltantes, sentando las bases para futuros análisis.

Este trabajo ha sido desarrollado por **Talento Tech** como parte del curso **Análisis de Datos Intermedio**.

---